version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:2.7.6-node
    steps:
      - checkout
      # - restore_cache:
      #     name: Restore Cache
      #     keys:
      #       - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "Gemfile.lock" }}
      #       - v1-dependencies
      # - run:
      #     name: Install Dependencies
      #     command: |
      #       yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      #       gem install bundler
      #       bundle install
      # - save_cache:
      #     name: Save Cache
      #     key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "Gemfile.lock" }}
      #     paths:
      #       - ~/.cache/yarn
      #       - ./vendor/bundle
      # - run:
      #     name: Setup Server
      #     command: |
      #       bundle exec rake contentful && bundle exec jekyll build
      # - run:
      #     name: Deploy
      #     command: |
      #       yarn netlify deploy --build --prod \
      #       --dir ./_site \
      #       --auth ${NETLIFY_AUTH_TOKEN} --site ${NETLIFY_SITE_ID}
      - run:
          name: Deploy
          command: |
            echo 'Deploy!'

  build-preview:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:2.7.6-node
    steps:
      - checkout
      # - restore_cache:
      #     name: Restore Cache
      #     keys:
      #       - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "Gemfile.lock" }}
      #       - v1-dependencies
      # - run:
      #     name: Install Dependencies
      #     command: |
      #       yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      #       gem install bundler
      #       bundle install
      # - save_cache:
      #     name: Save Cache
      #     key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "Gemfile.lock" }}
      #     paths:
      #       - ~/.cache/yarn
      #       - ./vendor/bundle
      # - run:
      #     name: Setup Server
      #     command: |
      #       bundle exec rake contentful && bundle exec jekyll build
      # - run:
      #     name: Deploy Preview
      #     command: |
      #       yarn netlify deploy --build --context deploy-preview \
      #       --dir ./_site \
      #       --auth ${NETLIFY_AUTH_TOKEN} --site ${NETLIFY_SITE_ID}
      - run:
          name: Deploy Preview
          command: |
            curl -X POST \
              -H "Content-Type:application/json" \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              -d "{\"body\":\"CircleCI TEST Deploy Preview\"}" \
              "https://api.github.com/repos/Tatehito/sample-comment-to-pr-from-circleci/issues/${CIRCLE_PULL_REQUEST##*/}/comments"

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - build-preview:
          filters:
            branches:
              ignore:
                - main
