version: 2.1

jobs:
  build-preview:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:2.7.6-node
    steps:
      - checkout
      - restore_cache:
          name: Restore Cache
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Cache
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./vendor/bundle
      # - run:
      #     name: Setup Server
      #     command: |
      #       bundle exec rake contentful && bundle exec jekyll build
      # - run:
      #     name: Deploy Preview
      #     command: |
      #       yarn netlify deploy --build --context deploy-preview \
      #       --dir ./_site \
      #       --auth ${NETLIFY_AUTH_TOKEN} --site ${NETLIFY_SITE_ID}
      - run:
          name: Deploy Preview Hoge
          command: |
            result=`echo "Website Draft URL:https://64061a6de8730706caf7bad0--scintillating-piroshki-928a9d.netlify.app"` &&
            echo "${result}" &&
            body=`echo "${result}" | grep 'Website Draft URL'` &&
            echo "{\"body\": \"${body}\"}" > body.json &&
            hoge=`cat body.json` &&
            echo ${hoge} &&
            curl -X POST \
              -H "Content-Type:application/json" \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              -d "${hoge}" \
              "https://api.github.com/repos/Tatehito/sample-comment-to-pr-from-circleci/issues/${CIRCLE_PULL_REQUEST##*/}/comments"
      - run:
          name: Deploy Preview
          command: |
            result=`yarn netlify deploy --build --context deploy-preview --dir ./_site --auth ${NETLIFY_AUTH_TOKEN} --site ${NETLIFY_SITE_ID}` &&
            echo "${result}" &&
            body=`echo "${result}" | grep 'Website Draft URL'` &&
            echo "{\"body\": \"${body}\"}" > body.json &&
            hoge=`cat body.json` &&
            echo ${hoge} &&
            curl -X POST \
              -H "Content-Type:application/json" \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              -d "${hoge}" \
              "https://api.github.com/repos/Tatehito/sample-comment-to-pr-from-circleci/issues/${CIRCLE_PULL_REQUEST##*/}/comments"

workflows:
  build:
    jobs:
      - build-preview:
          filters:
            branches:
              ignore:
                - main
